<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class BarangaysTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $barangays = [
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 4, 'barangay_name' => 'BONGBONG'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 4, 'barangay_name' => 'BUNGABONG'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 4, 'barangay_name' => 'KINGKING, NAPNAPAN, LAS ARANAS, ARAIBOL, TAGUGPO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 4, 'barangay_name' => 'MAGNAGA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 4, 'barangay_name' => 'MATIAO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 4, 'barangay_name' => 'P. FUENTES'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 4, 'barangay_name' => 'TAGDANGUA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 4, 'barangay_name' => 'TAMBONGAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 4, 'barangay_name' => 'TIBAGON'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 10, 'barangay_name' => 'ANDAP'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 10, 'barangay_name' => 'BANTACAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 10, 'barangay_name' => 'BATINAO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 10, 'barangay_name' => 'CABINUANGAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 10, 'barangay_name' => 'CAMANLANGAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 10, 'barangay_name' => 'COGONON'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 10, 'barangay_name' => 'FATIMA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 10, 'barangay_name' => 'KAHAYAG'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 10, 'barangay_name' => 'KATIPUNAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 10, 'barangay_name' => 'MAGANGIT'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 10, 'barangay_name' => 'MAGSAYSAY'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 10, 'barangay_name' => 'MAGSAYSAY BANTACAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 10, 'barangay_name' => 'MANURIGAO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 10, 'barangay_name' => 'PAGSABANGAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 10, 'barangay_name' => 'PANAG'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 10, 'barangay_name' => 'SAN ROQUE'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 10, 'barangay_name' => 'TANDAWAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'NEW SIBUNGA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'SAN ISIDRO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'MAINIT'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'CABADIANAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'SAN VICENTE'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'LIBASAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'SASA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'BASAK'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'MAGSAYSAY'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'BUKAL'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'TAGNOCON'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'ANISLAGAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'MANAT'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'ANTEQUERA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'NEW DAUIS'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'MAGADING'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'MAGSAYSAY'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'KATIPUNAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'MATILO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'CABACUNGAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'OGAO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'MAGADING'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'STO. NIRO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'BAYABAS'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'LINDA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'PANGUTOSAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'POBLACION'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'SAN ROQUE'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'STA. MARIA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 1, 'barangay_name' => 'MIPANGI'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 11, 'barangay_name' => 'BANGLASAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 11, 'barangay_name' => 'CONCEPCION'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 11, 'barangay_name' => 'PROSPERIDAD'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 11, 'barangay_name' => 'BANAG-BANAG'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 11, 'barangay_name' => 'BANKEROHAN NORTE'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 11, 'barangay_name' => 'BANKEROHAN SUR'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 11, 'barangay_name' => 'CAMANSI'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 11, 'barangay_name' => 'CAMANTANGAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 11, 'barangay_name' => 'CANIDKID'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 11, 'barangay_name' => 'DAUMAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 11, 'barangay_name' => 'LEBANON'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 11, 'barangay_name' => 'LINOAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 11, 'barangay_name' => 'NEW CALAPE'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 11, 'barangay_name' => 'NEW CEBULAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 11, 'barangay_name' => 'NEW DALAGUETE'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 11, 'barangay_name' => 'NEW VISAYAS'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 11, 'barangay_name' => 'SAN JOSE'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 11, 'barangay_name' => 'SAN VICENTE'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 11, 'barangay_name' => 'TAPIA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'AWAO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'BABAG'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'BANLAG'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'BAYLO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'CASSON'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'HAGUIMITAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'INAMBATAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => '5PA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'MAMONGA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'MT. DIWATA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'NABOC'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'OLAYCON'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'PASIAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'POBLACION'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'RIZAL'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'SALVACION'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'SAN ISIDRO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'SAN JOSE'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'TUBO-TUBO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'UNION'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 2, 'barangay_name' => 'UPPER ULIP'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 3, 'barangay_name' => 'ANDILI'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 3, 'barangay_name' => 'CONCEPCION'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 3, 'barangay_name' => 'NUEVO ILOCO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 3, 'barangay_name' => 'POBLACION'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 3, 'barangay_name' => 'SAWANGAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 3, 'barangay_name' => 'TUBURAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 3, 'barangay_name' => 'BAWANI'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 3, 'barangay_name' => 'MALINAWON'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 3, 'barangay_name' => 'SALVACION'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 3, 'barangay_name' => 'SAOSAO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'BAGONG SILANG'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'CAMBAGANG'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'CORONOBE'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'KATIPUNAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'LAHI'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'MABUGNAO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'MAGCAGONG'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'MAHAYAHAY'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'MAPAWA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'MAUSWAGON'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'NEW ALBAY'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'NEW KATIPUNAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'NEW MANAY'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'NEW PANAY'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'PALOC'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'PAMINTARAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'PARASAON'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'POBLACION'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'TALIAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'TANDIK'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'TIGBAO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 6, 'barangay_name' => 'TUPAS'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'ANIBONGAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'ANISLAGAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'BINUANGAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'BUCANA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'CALABLAB (PORT.)'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'CONCEPCION'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'DUMLAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'ELIZALDE (PORT.)'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'GUBATAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'HIJO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'KINIBAN (PORT.)'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'LANGGAM'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'LAPU-LAPU'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'LIBAY-LIBAY'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'LIMBO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'LUMATAB'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'MAGANGIT'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'MALAMUDAO (PORT.)'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'MANIPONGOL'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'MAPAANG'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'NEW ASTURIAS'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'NEW VISAYAS'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'PANANGAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'PANGI'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'PANIBASAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'PANORAON (PORT.)'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'POBLACION'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'SAB JUAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'SAN ROQUE'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'SANGAB'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'TAGBAROS (PORT.)'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 5, 'barangay_name' => 'TAGLAWIG'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 9, 'barangay_name' => 'ANITAPAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 9, 'barangay_name' => 'CABUYOAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 9, 'barangay_name' => 'CADUNAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 9, 'barangay_name' => 'CUAMBOG'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 9, 'barangay_name' => 'DEL PILAR'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 9, 'barangay_name' => 'GOLDEN VALLEY'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 9, 'barangay_name' => 'KOPIAT IS.'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 9, 'barangay_name' => 'LIBUDON'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 9, 'barangay_name' => 'LUNOD IS.'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 9, 'barangay_name' => 'PANGIBIRAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 9, 'barangay_name' => 'PINDASAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 9, 'barangay_name' => 'SAN ANTONIO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 9, 'barangay_name' => 'TAGNANAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'AGUINALDO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'AMORCRUZ'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'AMPAWID'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'ANDAP'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'ANITAP'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'BAGONG SILANG'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'BANBANON'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'BELMONTE'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'BINASBAS'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'BOLLUKAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'CEBOLEDA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'CONCEPCION'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'DATU AMPUNAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'DATU DAVAO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'DOAA JOSEFA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'IL KATIPUNAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'ILPAPA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'IMELDA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'INAKAYAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'KALIGUTAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'KAPATAGAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'KIDAWA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'KILAGDING'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'KIOKMAY'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'LANGTUD'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'LONGANAPAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'MABUHAY'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'MAKOPA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'MALALE'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'MALINAO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'MANGLOY'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'NAGA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'NEW BETHLEHEM'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'PANAMOREN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'POBLACION'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'SABUD'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'SAN ANTONIO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'SANTA EMILIA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'SISIMON'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 8, 'barangay_name' => 'STO. NIEO'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 7, 'barangay_name' => 'AURORA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 7, 'barangay_name' => 'BAGONGON'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 7, 'barangay_name' => 'GABI'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 7, 'barangay_name' => 'LAGAB'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 7, 'barangay_name' => 'MANGAYON'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 7, 'barangay_name' => 'MAPACA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 7, 'barangay_name' => 'MARAPAT'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 7, 'barangay_name' => 'NEW ALLEGRIA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 7, 'barangay_name' => 'NGAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 7, 'barangay_name' => 'OSMEOA'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 7, 'barangay_name' => 'PANANSALAN'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 7, 'barangay_name' => 'POBLACION'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 7, 'barangay_name' => 'SAN JOSE'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 7, 'barangay_name' => 'SAN MIGUEL'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 7, 'barangay_name' => 'SIOCON'],
            ['color' => '#0d0d0d', 'report_threshold' => 10, 'lat' => null, 'lng' => null, 'municipality_id' => 7, 'barangay_name' => 'TAMIA']
            // Add more barangays as needed
        ];
        //
        DB::table('barangays')->insert($barangays);
    }
}
